/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Fake <linux/export.h> for freestanding .ko builds.
 *
 * In freestanding mode, EXPORT_SYMBOL is a no-op — actual ksymtab
 * entries are generated by kh_crc / kh_exports.S.
 */

#ifndef _FAKE_LINUX_EXPORT_H
#define _FAKE_LINUX_EXPORT_H

#ifndef EXPORT_SYMBOL
#define EXPORT_SYMBOL(sym) /* freestanding: provided by kh_exports.S */
#endif

#endif /* _FAKE_LINUX_EXPORT_H */
